{{- range $i, $r := .Values.ingress.redirects -}}
{{- $code := default 301 $r.code -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "form-mailer.fullname" $ }}-redirect-{{ $i }}
  labels:
    {{- include "form-mailer.labels" $ | nindent 4 }}
  annotations:
    haproxy.org/request-redirect: "https://{{ $r.to }}"
    haproxy.org/request-redirect-code: {{ $code | quote }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - secretName: {{ include "form-mailer.fullname" $ }}-redirect-{{ $i }}-tls
      hosts:
        - {{ $r.from | quote }}
  rules:
    - host: {{ $r.from | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "form-mailer.fullname" $ }}
                port:
                  name: http
{{ end }}
